<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">testCaseSetUp</value>
  <value name="encodeutf8">true</value>
  <value name="body">LyoKICogQ3JlYXRpbmcgYSBEdXJhYmxlIER1YnNjcmliZXIgdXNpbmcgY29uc3VtZXIgc2Vydmlj
ZQogKi8KIApTdHJpbmcgdGVzdE5hbWUgICAgICAgICAgICA9ICJUZXN0Q2FzZTE0IjsgClN0cmlu
ZyBkZXNjcmlwdGlvbiAgICAgICAgID0gIkNyZWF0aW5nIER1cmFibGUgU3Vic2NyaWJlciAtIFRv
cGljcyI7ClN0cmluZyBjb25uZWN0aW9uQWxpYXNOYW1lID0gIkJyb2tlckFfTlRfVCI7ClN0cmlu
ZyBkZXN0aW5hdGlvbk5hbWUgICAgID0gIlRvcGljMyI7IC8vU2hhcmVkIFN0YXRlOiB0cnVlOyBT
aGFyZWQgU3RhdGUgT3JkZXJpbmc6IG5vbmVdCmludCBjb3VudCAgICAgICAgICAgICAgICAgID0g
MTsKaW50IHRpbWVvdXQgICAgICAgICAgICAgICAgPSAzMDAwOwoKLy8gc2V0IHRlc3QgaW5wdXQK
SURhdGFDdXJzb3IgaWMgPSBwaXBlbGluZS5nZXRDdXJzb3IoKTsKSURhdGFVdGlsLnB1dChpYywg
InRlc3ROYW1lIiwgdGVzdE5hbWUpOwpJRGF0YVV0aWwucHV0KGljLCAiZGVzY3JpcHRpb24iLCBk
ZXNjcmlwdGlvbik7CklEYXRhVXRpbC5wdXQoaWMsICJjb25uZWN0aW9uQWxpYXNOYW1lIiwgY29u
bmVjdGlvbkFsaWFzTmFtZSk7CklEYXRhVXRpbC5wdXQoaWMsICJkZXN0aW5hdGlvbk5hbWUiLCBk
ZXN0aW5hdGlvbk5hbWUpOwpJRGF0YVV0aWwucHV0KGljLCAiY291bnQiLCBjb3VudCk7CklEYXRh
VXRpbC5wdXQoaWMsICJyZXBlYXQiLCBTdHJpbmcudmFsdWVPZihjb3VudCAtIDEpKTsKSURhdGFV
dGlsLnB1dChpYywgInRpbWVvdXQiLCB0aW1lb3V0KTsKCg==</value>
</Values>
