<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">readme</value>
  <value name="encodeutf8">true</value>
  <value name="body">LyoKCkpNUyBKUUEgVGVzdCBIYXJuZXNzIGNhbiBiZSB1c2VkIHRvIHJ1biBpbmRpdmlkdWFsIHRl
c3QgY2FzZXMgKHNlZSAqLnJ1blRlc3RDYXNlKSAKb3IgYW4gZW50aXJlIHRlc3Qgc3VpdGUgKHNl
ZSAqLnJ1blRlc3RTdWl0ZSkuIFRoZSBvdXRwdXQgb2YgZWFjaCB0ZXN0IHdpbGwgYmUgCndyaXR0
ZW4gdG8gYSByb3RhdGluZyBsb2cgZmlsZSBsb2NhdGVkIGluIHRoZSBcbG9ncyBkaXJlY3Rvcnku
IEVhY2ggdGVzdCBjYXNlIHdpbGwgCmFsc28gcmV0dXJuIG91dHB1dCBpbiB0aGUgZm9ybSBvZiBY
TUwgc28gdGhlIHRlc3RzIGNhbiBiZSBjYWxsZWQgZXh0ZXJuYWxseSAoZS5nLiAKYnkgSk1ldGVy
KS4KCkpNUyBKUUEgVGVzdCBIYXJuZXNzIGluY2x1ZGVzIHggdGVzdCBzdWl0ZXM6CgogICAgcXVl
dWVUZXN0U3VpdGUgLSByZXNwb25zaWJsZSBmb3IgdGVzdGluZyB0aGUgYmFzaWMgSk1TIFF1ZXVl
IGZ1bmN0aW9uYWxpdHkuCiAgICBUaGlzIHRlc3Qgc3VpdGUgcmVxdWlyZXMgcXVldWUxIC0gcXVl
dWU3LgoKICAgIHRvcGljVGVzdFN1aXRlIC0gcmVzcG9uc2libGUgZm9yIHRlc3RpbmcgdGhlIGJh
c2ljIEpNUyBUb3BpYyBmdW5jdGlvbmFsaXR5LgoKICAgIC4uLi4KCiov</value>
</Values>
