<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">testCaseSetUp</value>
  <value name="encodeutf8">true</value>
  <value name="body">LyoKICogU2VuZCAmIFJlY2VjaXZpbmcgTWVzc2FnZSBzdHJlYW0gUHVibGljIFNlcnZpY2UgLSBB
dWRpbyBGaWxlCiAqIFdlIGFyZSB1c2luZyBEdXJhYmxlIFN1YnNjcmliZXIgdG8gcmVjZWl2ZSB0
aGUgbWVzc2FnZQogKi8KIApTdHJpbmcgdGVzdE5hbWUgICAgICAgICAgICA9ICJUZXN0Q2FzZTE3
IjsgClN0cmluZyBkZXNjcmlwdGlvbiAgICAgICAgID0gIkxhcmdlIE1lc3NhZ2UgU3RyZWFtIC0g
VG9waWMgVGVzdCI7ClN0cmluZyBjb25uZWN0aW9uQWxpYXNOYW1lID0gIkJyb2tlckFfTlRfVCI7
ClN0cmluZyBkZXN0aW5hdGlvbk5hbWUgICAgID0gIlRvcGljMyI7IC8vU2hhcmVkIFN0YXRlOiB0
cnVlOyBTaGFyZWQgU3RhdGUgT3JkZXJpbmc6IG5vbmVdCmludCBjb3VudCAgICAgICAgICAgICAg
ICAgID0gMTsKaW50IHRpbWVvdXQgICAgICAgICAgICAgICAgPSAzMDAwOwoKLy8gc2V0IHRlc3Qg
aW5wdXQKSURhdGFDdXJzb3IgaWMgPSBwaXBlbGluZS5nZXRDdXJzb3IoKTsKSURhdGFVdGlsLnB1
dChpYywgInRlc3ROYW1lIiwgdGVzdE5hbWUpOwpJRGF0YVV0aWwucHV0KGljLCAiZGVzY3JpcHRp
b24iLCBkZXNjcmlwdGlvbik7CklEYXRhVXRpbC5wdXQoaWMsICJjb25uZWN0aW9uQWxpYXNOYW1l
IiwgY29ubmVjdGlvbkFsaWFzTmFtZSk7CklEYXRhVXRpbC5wdXQoaWMsICJkZXN0aW5hdGlvbk5h
bWUiLCBkZXN0aW5hdGlvbk5hbWUpOwpJRGF0YVV0aWwucHV0KGljLCAiY291bnQiLCBjb3VudCk7
CklEYXRhVXRpbC5wdXQoaWMsICJ0aW1lb3V0IiwgdGltZW91dCk7Cgo=</value>
</Values>
