<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">countDownAndValidate</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgaWMgPSBwaXBlbGluZS5nZXRDdXJzb3IoKTsNClN0cmluZyB0ZXN0TmFtZSA9
IElEYXRhVXRpbC5nZXRTdHJpbmcoaWMsICJ0ZXN0TmFtZSIpOw0KU3RyaW5nIHJlc3VsdHMgPSBJ
RGF0YVV0aWwuZ2V0U3RyaW5nKGljLCAicmVzdWx0cyIpOw0KaWMuZGVzdHJveSgpOw0KDQppZiAo
dGVzdE5hbWUgPT0gbnVsbCB8fCB0ZXN0TmFtZS5sZW5ndGgoKSA8IDEpIHsNCiAgICB0aHJvdyBu
ZXcgU2VydmljZUV4Y2VwdGlvbigibWlzc2luZyByZXF1aXJlZCBmaWVsZDogdGVzdE5hbWUiKTsN
Cn0NCg0KSW50ZWdyYXRpb25UZXN0IHRlc3QgPSBJbnRlZ3JhdGlvblRlc3RNYXAuZ2V0SW5zdGFu
Y2UoKS5nZXRJbnRlZ3JhdGlvblRlc3QodGVzdE5hbWUpOwppZiAodGVzdCAhPSBudWxsKSB7DQog
ICAgdGVzdC5jb3VudERvd25BbmRWYWxpZGF0ZShyZXN1bHRzKTsNCn0NCg==</value>
</Values>
